#!/usr/bin/env python3
import time as t
import random
import colors as c
print(c.clear + '''
He who would cross the Bridge of Death
Must answer me these questions three,
Ere the other side he see.
''' + c.reset)

def prompt(question):
    print(c.green + question)
    answer = input('> ' + c.blue)
    answer = answer.lower().strip()
    print(c.reset)
    return answer

def die():
    print("Thou art cast into the Gorge of Eternal Peril")
    exit()

def live():
    print("Right, off you go then")

name = prompt("What is your name?")
quest = prompt("What is your quest?")

if name in  ["lancelot", "galahad"]:
    color = prompt("What is your favourite colour?")
    if " no " in color:
        die()
    live()

elif name == "Robin":
    pass
elif name == "Galahad":
    pass
elif name == "Arthur":
    pass
else:
    pass #everyone else
