#!/usr/bin/env python3


text = '''
There was {} in the world. So God told Noah that it was going to {}
for a {} time. God gave Noah {} on what to do: "Make a {}. It
should be made out of gopher {} and should be {} {} long, and
75 {} wide. Take with you {} of every creature: One {},
and one female." So Noah gathered his {} together, and they
{} the ark. Noah`s friends {} out {} at him as
he worked, but Noah didn`t pay attention to them. Finally after 120
{}, the ark was {}. They then gathered all the creatures,
and as the last one boarded, it began to {}. For 40 {}
and 40 {}, it went on. The Earth became covered with {}. After a year
and a day, they found {}, and everyone else was {}. And as a sign
that God would never {} the Earth again, he gave them a/an {}.
'''

words = [
    'noun',
    'verb',
    'adjective',
    'noun (plural)',
    'vehicle',
    'noun',
    'number',
    'noun (plural)',
    'noun (plural)',
    'number',
    'adjective',
    'noun',
    'verb ending in "ed"',
    'verb ending in "ed"',
    'noun (plural)',
    'measurement of time (plural)',
    'verb ending in "ed"',
    'noun (plural)',
    'noun (plural)',
    'type of liquid',
    'noun',
    'adjective',
    'verb',
    'noun',
]
