#!/usr/bin/env python3
import colors as c
import time as t
import random as r

'''
What number do you need?
'''

n = input('Which number? ')
print('Here is your ' + n + ' multiplication tables.')
   
for count in range(1,13):
    print(count, end=' * ' + n + ' =  ')
    print(int(n) * count)
    
