#!/usr/bin/env python3

import colors as c
import time as t

print(c.pink + '''
Welcome to the Pink Fluffy Unicorns Quiz Game!!!
''' + c.reset)

for verse in range(8):
    print(c.pink + "Pink Fluffy Unicorns Dancing on Rainbows")
    t.sleep(1)
print("Let's test your knowledge and see what you've learned so far!!!")
print("What color are the Unicorns?")
answer = input(c.pink + '--> ')
if answer in ("pink"):
    print("Correct!")
else:
    print("Incorrect. I HOPE YOU DIE IN A FIRE!!!")
print("What are they dancing on?")
answer = input(c.pink + '---> ')
if answer in ("refracted light"):
    print("Correct!")
elif answer in ("rainbows"):
    print(c.red + "NO, IT'S REFRACTED LIGHT!")
else:
    print("Incorrect. I HOPE YOU DIE IN A FIRE!")
print("Use one word to describe the texture of their magical fur.")
answer = input(c.pink + '---> ')
if answer in ["smiles", "fluffy"]:
    print("Correct!")
else:
    print("Incorrect. I HOPE YOU DIE IN A FIRE!")
