#!/usr/bin/env python3

import random as r
import colors as c
import time as t
from utils import ask

print(c.clear + c.pink + '''
Welcome to the Pink Fluffy Unicorns Quiz Game!!!
''' + c.reset)
'''
for verse in range(8):
    print(c.pink + "Pink Fluffy Unicorns Dancing on Rainbows")
    t.sleep(3.8)
print("Let's test your knowledge and see what you've learned so far!!!")
'''
def q1():
    answer = ask("What color are the Unicorns?")
    if answer == "pink":    
        return True
    return False

def q2():
    answer = ask("What are they dancing on?")
    if answer.startswith == "refracted light":
        return True
    return False

def q3():
    answer = ask("Use one word to describe the texture of their magical fur.")
    if answer.startswith == "smiles":
        return True
    return False

qs = [q1,q2,q3]
while qs:
    q = r.choice(qs)
    answer = q()
    if answer:
        qs.remove(q)
